name: Go Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile Go Code
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: yourusername
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: yourdatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U yourusername -d yourdatabase; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://yourusername:yourpassword@localhost:5432/yourdatabase?sslmode=disable" >> $GITHUB_ENV

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
