name: Go Build Check

on:
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Compile Go Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...