name: Packer CI before merging

on:
    pull_request:
      branches:
        - main

jobs:
  packer-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run packer fmt
        run: packer fmt .
      - name: Check for formatting changes
        run: git diff --exit-code
        shell: bash

  packer-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
      - name: Run packer init
        run: packer init .
      - name: Run packer validate
        run: packer validate .
